version: '3.8'

services:
  vaultwarden:
    network_mode: "bridge"
    container_name: vaultwarden
    image: vaultwarden/server:latest
    restart: always
    volumes:
      - ./data/:/data/
    ports:
      - 80:80
    environment:
      - DOMAIN=http://<server-ip>
      - LOGIN_RATELIMIT_MAX_BURST=10
      - LOGIN_RATELIMIT_SECONDS=60
      - ADMIN_RATELIMIT_MAX_BURST=10
      - ADMIN_RATELIMIT_SECONDS=60
      - ADMIN_TOKEN=PaSsWoRd
      - SENDS_ALLOWED=true
      - SIGNUPS_ALLOWED=false
      - EMERGENCY_ACCESS_ALLOWED=true
      - WEB_VAULT_ENABLED=true
