services:
  monitoring:
    network_mode: "host"
    container_name: monitoring
    image: nicolargo/glances:latest
    restart: always
    environment:
      - "GLANCES_OPT=-w"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    pid: "host"
