version: "3.8"
services:
  dashy:
    image: lissy93/dashy:latest
    container_name: dashy
    volumes:
      - ./public/config.yml:/app/public/conf.yml
    ports:
      - 4000:80
    environment:
      - NODE_ENV=production
    restart: always
