version: "3.8"
services:
  dashy:
    network_mode: "bridge"
    image: ghcr.io/lissy93/dashy:latest
    container_name: dashy
    volumes:
      - ./public/conf.yml:/app/public/conf.yml
    ports:
      - 4000:80
    environment:
      - NODE_ENV=production
    restart: always
