services:
  wg-easy:
    network_mode: "host"
    environment:
      - WG_HOST=${wg_host}
      - PASSWORD=${wg_pwd}
      - WG_DEFAULT_ADDRESS=${wg_address}
      - WG_DEFAULT_DNS=${wg_dns}
      - WG_PERSISTENT_KEEPALIVE=${wg_keepalive}
      - UI_TRAFFIC_STATS=${traffic_stats}
      - UI_CHART_TYPE=${chart}
    image: ghcr.io/wg-easy/wg-easy:latest
    container_name: wireguard
    volumes:
      - .:/etc/wireguard
    restart: always
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
