version: "3.8"
services:
  wg-easy:
    network_mode: "host"
    environment:
      - WG_HOST=<dyndns>
      - PASSWORD=${PWD}
      - WG_PORT=51820
      - WG_DEFAULT_ADDRESS_IPV4=10.8.0.x
      - WG_DEFAULT_DNS=<dns>
      - WG_PERSISTENT_KEEPALIVE=25

    image: ghcr.io/wg-easy/wg-easy:latest
    container_name: wireguard
    volumes:
      - .:/etc/wireguard
    restart: always
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
